DataTest/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
# Configuration Dash

urlpatterns = [
# Configuration requise pour django-plotly-dash
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('', views.home, name='home'),

    path('scholar_and_cv/', views.scholar_and_cv, name='scholar_and_cv'),
    path('polls/', include('polls.urls')),
    path('agri/', include('agri.urls')),
    path('admin/', admin.site.urls),
    path('graph/', include('graph.urls')),
    path('bubble_sort/', include('bubble_sort.urls')),
    # Intégration de l'app Dash sous le préfixe 'agri/demo/'
    path('agri/demo/', include([
    path('', include('dashapp.urls', namespace='dashapp')),  # Correction clé
    path('/api/', include('dashapp.urls', 'api')),  # Inclusion du namespace API
    path('dash-components/', include('django_plotly_dash.urls')),  # Routes Dash
    ])),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agri/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# Configuration Dash

urlpatterns = [
    path('', views.home, name='app_presentation'),
    path('demo/', views.ParcelView.as_view(), name='parcel_viewer'),
    path('ndvi/', views.NDVIView.as_view(), name='ndvi_view'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashapp/urls.py
from django.urls import path
from . import views

app_name = 'dashapp'

urlpatterns = [
    path('parcelles/', views.dash_view, name='parcelle_analysis'),
path('api/ml-pipeline/', views.process_ml_pipeline, name='ml_pipeline'),

path('api/save-points/', views.save_points, name='save_points'),
    path('ml-results/<uuid:train_result_id>/<uuid:pred_result_id>/',  # Ajout des UUID
         views.ml_results_view,
         name='ml_results'),
]

graph/urls.py
from django.urls import path

from . import views

app_name = 'graph'
urlpatterns = [
    path('', views.CourseList.as_view(), name='index'),
    path('course/<int:pk>/resultats/', views.ResultatsCourseView.as_view(), name='resultats_course'),
    path(r'vitesse-distribution/', views.VitesseDistributionView.as_view(), name='vitesse_distribution'),

    path('score-distribution/', views.ScoreDistributionView.as_view(), name='score_distribution'),
    path('stat-global/', views.StatGlobalView.as_view(), name='stat_global'),
    path('coureur/<int:pk>/', views.CoureurDetailView.as_view(), name='coureur_detail'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    ]

graph/views.py
from datetime import time
from .utils.plot_utils import generate_figure, get_base_data, get_more_data, generate_score_plot, evolution_types_courses, evolution_vitesse_par_categorie, evolution_vitesse_par_categorie_data
from django.core.serializers import serialize
from django.shortcuts import render
from django.utils.decorators import method_decorator
from scipy.stats import skew, kurtosis
from django.db.models import Subquery, OuterRef
from .models import Course, Categorie, CoureurCategorie, Coureur, ResultatCourse, CourseType, CategorieSimplifiee, ColorPreset
from django.views import generic
import plotly.graph_objects as go
from django.views.generic import TemplateView
from django.http import JsonResponse, HttpResponse
import numpy as np
import pandas as pd
import plotly.graph_objs as go
from random import sample
from django.template.loader import render_to_string
from django.views import generic
from django.db.models import F, ExpressionWrapper, FloatField
from django.db.models.functions import Cast
from django.views.generic import DetailView
from django.db.models import Prefetch
from django.db.models import Q
from django.core.serializers.json import DjangoJSONEncoder
import json
from django.db.models import F, ExpressionWrapper, DurationField, FloatField
from django.views.decorators.csrf import csrf_exempt
import ast
import re
from plotly.offline import plot
import plotly.express as px
from graph.utils.final_plot import *
from decimal import Decimal
from datetime import date

# Sérialisation personnalisée
def custom_serializer(obj):
    if isinstance(obj, Decimal):
        return float(obj)
    if isinstance(obj, (date, np.datetime64)):
        return str(obj)
    raise TypeError(f"Type {type(obj)} non géré")

class CourseList(generic.ListView):
    template_name = 'graph/index.html'
    context_object_name = 'nom_list'
    paginate_by = 50  # Si vous voulez la pagination

    def normalize_and_split(self, text):
        """Nettoie le texte en supprimant les chiffres et caractères non alphanumériques, puis le sépare en mots."""
        # Supprime tous les chiffres
        text = re.sub(r'\d+', '', text)
        # Remplace les caractères non alphanumériques par des espaces
        text = re.sub(r'\W+', ' ', text)
        # Convertit en minuscule pour une comparaison insensible à la casse
        text = text.lower()
        # Sépare en mots
        return text.split()

    def get_queryset(self):
        """Return all finishers, ordered by their finish time."""
        search_course = self.request.GET.get('search_course', '').strip()
        search_coureur = self.request.GET.get('search_coureur', '').strip()
        # Filtrer par nom de course si un terme est fourni
        if search_course:
            queryset = queryset.filter(
                Q(course__nom__iexact=search_course) | Q(course__nom_marsien__iexact=search_course)
            )

        # Filtrer par nom de coureur si un terme est fourni
        if search_coureur:
            queryset = queryset.filter(
                Q(coureur__nom__iexact=search_coureur) | Q(coureur__prenom__iexact=search_coureur) |
                Q(coureur__nom_marsien__iexact=search_coureur) | Q(coureur__prenom_marsien__iexact=search_coureur)
            )

        return Course.objects.all().order_by('nom_marsien').distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object_list:
            context['field_names'] = ['Nom', 'Année', 'Distance', 'Type']
        return context


class ResultatsCourseView(generic.ListView):
    template_name = 'graph/resultats_course.html'
    context_object_name = 'resultats_list'
    paginate_by = 50


    def get_queryset(self):
        course_id = self.kwargs['pk']

        return ResultatCourse.objects.filter(course_id=course_id).annotate(
            total_seconds=ExpressionWrapper(Cast(F('temps'), FloatField()) / 1000000.0, output_field=FloatField()),
            total_seconds2=ExpressionWrapper(Cast(F('temps2'), FloatField()) / 1000000.0, output_field=FloatField()),
            vitesse=ExpressionWrapper(
                (F('course__distance') / (F('total_seconds') + 0.000001))*3.6,  # Ajout d'une petite valeur pour éviter la division par zéro
                output_field=FloatField()
            ),
            vitesse2=ExpressionWrapper(
                (F('course__distance') / (F('total_seconds2') + 0.000001))*3.6,  # Ajout d'une petite valeur pour éviter la division par zéro
                output_field=FloatField()
            )
        ).order_by('position')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = Course.objects.get(pk=self.kwargs['pk'])
        return context


class SearchResultsView(TemplateView):
    template_name = 'graph/search_results.html'

    def normalize_and_split(self, text):
        """Nettoie le texte en supprimant les chiffres et caractères non alphanumériques, puis le sépare en mots."""
        text = re.sub(r'\d+', '', text)  # Supprime les chiffres
        text = re.sub(r'\W+', ' ', text)  # Remplace les caractères non alphanumériques par des espaces
        return text.lower().split()  # Convertit en minuscule et divise en mots

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Récupérer les paramètres GET
        search_course = self.request.GET.get('search_course', '').strip()
        search_coureur = self.request.GET.get('search_coureur', '').strip()

        courses_results = Course.objects.none()
        coureurs_results = Coureur.objects.none()

        if search_course:
            # Normaliser et diviser la requête en mots
            normalized_words = self.normalize_and_split(search_course)
            courses_results = Course.objects.filter(
                Q(nom__iregex=r'\b(?:' + '|'.join(normalized_words) + r')\b') |
                Q(nom_marsien__iregex=r'\b(?:' + '|'.join(normalized_words) + r')\b')
            )

        if search_coureur:
            # Normaliser et diviser la requête en mots
            normalized_words = self.normalize_and_split(search_coureur)
            coureurs_results = Coureur.objects.filter(
                Q(nom__iregex=r'\b(?:' + '|'.join(normalized_words) + r')\b') |
                Q(prenom__iregex=r'\b(?:' + '|'.join(normalized_words) + r')\b') |
                Q(nom_marsien__iregex=r'\b(?:' + '|'.join(normalized_words) + r')\b') |
                Q(prenom_marsien__iregex=r'\b(?:' + '|'.join(normalized_words) + r')\b')
            )

        # Ajouter les résultats au contexte
        context['courses_results'] = courses_results
        context['coureurs_results'] = coureurs_results
        context['search_course'] = search_course  # Pour afficher dans le formulaire
        context['search_coureur'] = search_coureur  # Pour afficher dans le formulaire

        return context

class CoureurDetailView(DetailView):
    model = Coureur
    template_name = 'graph/coureur_detail.html'
    context_object_name = 'coureur'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        coureur = self.object

        # Récupérer tous les résultats de course pour ce coureur, avec les informations de course préchargées
        resultats = ResultatCourse.objects.filter(coureur=coureur).select_related('course').order_by('-course__annee', 'course__nom_marsien')

        # Récupérer toutes les catégories du coureur, groupées par année
        categories = CoureurCategorie.objects.filter(coureur=coureur).select_related('categorie').order_by('-annee')

        # Créer un dictionnaire des catégories par année
        categories_par_annee = {}
        for cat in categories:
            if cat.annee not in categories_par_annee:
                categories_par_annee[cat.annee] = []
            categories_par_annee[cat.annee].append(cat.categorie)

        # Ajouter les catégories à chaque résultat de course
        for resultat in resultats:
            resultat.categories = categories_par_annee.get(resultat.course.annee, [])

        context['resultats'] = resultats
        context['categories_par_annee'] = categories_par_annee
        return context


@method_decorator(csrf_exempt, name='dispatch')
class VitesseDistributionView(TemplateView):
    template_name = 'graph/vitesse_distribution.html'

    def safe_literal_eval(self, data):
        if isinstance(data, list):
            return data
        try:
            # Essayer d'évaluer directement avec literal_eval
            return ast.literal_eval(data)
        except (ValueError, SyntaxError):
            # Si une erreur survient, nettoyer les guillemets superflus et réessayer
            try:
                cleaned_data = data.strip("'\"[]")  # Supprime les guillemets simples ou doubles
                return [cleaned_data]  # Remettre dans une liste
            except Exception as e:
                # En dernier recours, retourner une liste vide ou une valeur par défaut
                return ["Course sur route", "Foulee"]

    def filter_by_series(self, data, series_categories):
        dataframes_by_series = {}

        for series_name, filters in series_categories.items():
            sexe_filter = filters.get('sexe', [])
            nom_filter = filters.get('nom', [])

            filtered_data = data[
                (data['sexe'].apply(
                    lambda x: not sexe_filter or (x is not None and any(sexe in sexe_filter for sexe in [x])))) &
                (data['nom_categorie'].apply(
                    lambda x: not nom_filter or (x is not None and any(cat in nom_filter for cat in [x]))))
                ]

            dataframes_by_series[series_name] = filtered_data

        return dataframes_by_series

    def calculate_stats(self, dataframes_by_series):
        stats = {
            'distances': {},
            'vitesses': {}
        }

graph/templates/graph/coureur_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h1>{{ coureur.prenom_marsien }} {{ coureur.nom_marsien }}</h1>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% if coureur.score_de_viabilite %}
        <p>Score de viabilité : {{ coureur.score_de_viabilite }}</p>
    {% endif %}

    <h2>Catégories par année</h2>
    {% for annee, categories in categories_par_annee.items %}
        <p>{{ annee }} : {% for categorie in categories %}{{ categorie.nom }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    {% empty %}
        <p>Aucune catégorie enregistrée pour ce coureur.</p>
    {% endfor %}

    <h2>Participations aux courses</h2>
    {% if resultats %}
        <div class="course-list">
            <div class="course-row course-header">
                <div class="course-cell">Course</div>
                <div class="course-cell">Année</div>
                <div class="course-cell">Catégorie(s)</div>
                <div class="course-cell">Position</div>
             </div>
            {% for resultat in resultats %}
                <div class="course-row course-item">
                    <div class="course-cell">{{ resultat.course.nom_marsien }}</div>
                    <div class="course-cell">{{ resultat.course.annee }}</div>
                    <div class="course-cell">
                        {% for categorie in resultat.categories %}
                            {{ categorie.nom }}{% if not forloop.last %}, {% endif %}
                        {% empty %}
                            -
                        {% endfor %}
                    </div>
                    <div class="course-cell">{{ resultat.position }}</div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Ce coureur n'a participé à aucune course.</p>
    {% endif %}
    
    <a href="{% url 'graph:index' %}" class="btn btn-secondary">Retour à la liste des courses</a>
{% endblock %}

graph/templates/graph/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="page-content" style="margin: 20px;">
<h2>Liste des courses</h2>
<div class="button-container">
    <a href="{% url 'graph:vitesse_distribution' %}" id="btn-primary">Voir la distribution des vitesses</a>
    <a href="{% url 'graph:score_distribution' %}" id="btn-secondary">Voir l'évolution des scores de performance</a>
    <a href="{% url 'graph:stat_global' %}" id="btn-tertiary">Voir des statistiques globales sur les données</a>
</div>
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <form method="get" action="{% url 'graph:search_results' %}">
    <div>
        <label for="search_course">Rechercher par nom de course :</label>
        <input type="text" id="search_course" name="search_course" placeholder="Nom de la course">
    </div>
    <div>
        <label for="search_coureur">Rechercher par nom de coureur :</label>
        <input type="text" id="search_coureur" name="search_coureur" placeholder="Nom du coureur">
    </div>
    <button type="submit">Rechercher</button>
</form>
{% if nom_list %}
    <div class="course-list">
        <div class="course-row course-header">
            <div class="course-cell">Nom</div>
            <div class="course-cell">Année</div>
            <div class="course-cell">Distance</div>
            <div class="course-cell">Type</div>
        </div>
        {% for course in nom_list %}
            <a href="{% url 'graph:resultats_course' course.id %}" class="course-row course-item">
                <div class="course-cell">{{ course.nom_marsien }}</div>
                <div class="course-cell">{{ course.annee }}</div>
                <div class="course-cell">{{ course.distance }}</div>
                <div class="course-cell">{{ course.type.nom }}</div>
            </a>
        {% endfor %}
    </div>
    {% if is_paginated %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; première</a>
                    <a href="?page={{ page_obj.previous_page_number }}">précédente</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">suivante</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">dernière &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% else %}
    <p>Aucune course n'est disponible.</p>
{% endif %}
    </div>
{% endblock %}

graph/templates/graph/partial_vitesse_distribution.html
{% load static %}
<div id="chart-container" style="width: 98%; height: 500px;">
    {{ plot|safe }}
</div>
<script>console.log("Chart Config Stats:", JSON.stringify(window.chartConfig.stats, null, 2))</script>
<div id="statistics-container">
    <h3>Statistiques</h3>
        <div id="dynamic-stats-container"></div>
</div>
<div id="progress-info-container">
    <div id="progress-info">
        Résultats traités : <span id="loaded-count">{{ loaded_count }}</span> / <span id="total-count">{{ total_count }}</span>
    </div>
    <div id="countdown">Chargement du compte à rebours...</div>
</div>
    <script src="{% static 'js/dynamicStat.js' %}"></script>
<script src="{% static 'js/chart_update.js' %}"></script>
    <script src="{% static 'js/buttoncat.js' %}"></script>

graph/templates/graph/resultats_course.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h2>Résultats de la course : {{ course.nom_marsien }} ({{ course.annee }})</h2>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% if resultats_list %}
        <div class="course-list">
    <div class="course-row course-header">
        <div class="course-cell">Position</div>
        <div class="course-cell">Coureur (Marsien)</div>
        <div class="course-cell">Temps</div>
        <div class="course-cell">Temps2</div>
        <div class="course-cell">Vitesse</div>
        <div class="course-cell">Vitesse2</div>
    </div>
    {% for resultat in resultats_list %}
        <a href="{% url 'graph:coureur_detail' resultat.coureur.id %}" class="course-row course-item {% if resultat.coureur.score_de_viabilite %}orange-row{% endif %}">
            <div class="course-cell">{{ resultat.position }}</div>
            <div class="course-cell">
                {% if resultat.coureur.nom_marsien %}
                    {{ resultat.coureur.nom_marsien }}
                {% endif %}
                {% if resultat.coureur.prenom_marsien %}
                    {{ resultat.coureur.prenom_marsien }}
                {% endif %}
            </div>
            <div class="course-cell">{{ resultat.temps|default_if_none:"-" }}</div>
            <div class="course-cell">{{ resultat.temps2|default_if_none:"-" }}</div>
            <div class="course-cell">{{ resultat.vitesse|floatformat:4|default_if_none:"-" }}</div>
            <div class="course-cell">{{ resultat.vitesse2|floatformat:4|default_if_none:"-" }}</div>
                </a>
        {% endfor %}
            </div>

        {% if is_paginated %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; première</a>
                    <a href="?page={{ page_obj.previous_page_number }}">précédente</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">suivante</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">dernière &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    {% else %}
        <p>Aucun résultat n'est disponible pour cette course.</p>
    {% endif %}
    <a href="{% url 'graph:index' %}" class="btn btn-secondary">Retour à la liste des courses</a>
{% endblock %}

graph/templates/graph/search_results.html
{% extends "base.html" %}

{% block content %}
    <h2>Résultats de la recherche</h2>

    <!-- Formulaire pour affiner ou relancer une recherche -->
    <form method="get" action="{% url 'graph:search_results' %}">
        <div>
            <label for="search_course">Rechercher par nom de course :</label>
            <input type="text" id="search_course" name="search_course" value="{{ search_course }}">
        </div>
        <div>
            <label for="search_coureur">Rechercher par nom de coureur :</label>
            <input type="text" id="search_coureur" name="search_coureur" value="{{ search_coureur }}">
        </div>
        <button type="submit">Rechercher</button>
    </form>

    {% if not courses_results and not coureurs_results %}
        <p>Aucun résultat trouvé.</p>
    {% else %}
        <!-- Résultats des courses -->
        {% if courses_results %}
            <h2>Courses</h2>
            <ul>
                {% for course in courses_results %}
                    <li>{{ course.nom }} (Marsien : {{ course.nom_marsien }}, Année : {{ course.annee }})</li>
                {% endfor %}
            </ul>
        {% endif %}

        <!-- Résultats des coureurs -->
        {% if coureurs_results %}
            <h2>Coureurs</h2>
            <ul>
                {% for coureur in coureurs_results %}
                    <li>{{ coureur.prenom }} {{ coureur.nom }}
                        (Marsien : {{ coureur.prenom_marsien }} {{ coureur.nom_marsien }})
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endif %}

    <!-- Bouton retour -->
    <a href="{% url 'graph:index' %}" class="btn btn-secondary">Retour à l'accueil</a>
{% endblock %}

graph/templates/graph/stat_global.html
{% extends "base.html" %}
{% load static %}

{% block content %}
            <!-- Colonne de gauche -->
   <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <div class="graph-wrapper">
        <div class="graph-left">
    <h2>Évolution des types de courses par année</h2>
    <div class="chart-container">
        {{ plot_html|safe }}
    </div>
    
    <style>
        .chart-container {
            max-width: 660px;
        }
    </style>
        </div>
            <!-- Colonne de droite -->
        <div class="graph-right">
<h2>Evolution de la vitesse moyenne du 10 km et semi-marathon pour la catégorie choisie</h2>
<!-- Sélection de catégorie (sans formulaire complet) -->
<div class="form-container">
    <div class="form-group">
        <label for="categorie">Sélectionner une catégorie:</label>
        <select name="categorie" id="categorie" class="form-control">
            <option value="">-- Choisir une catégorie --</option>
            {% for categorie in categories %}
                <option value="{{ categorie.id }}" {% if selected_categorie == categorie.id %}selected{% endif %}>
                    {{ categorie.nom }}  âge : {{ categorie.age_min }} à {{ categorie.age_max }}
                </option>
            {% endfor %}
        </select>
    </div>
</div>

<!-- Indicateur de chargement -->
<div id="loading-indicator" style="display: none;">
    Chargement en cours...
</div>

<!-- Conteneur pour le graphique de vitesse -->
<div class="js-plotly-plot" id="vitesse-global">
    {{ vitesse_plot_html|safe }}
</div>
    <script src="{% static 'js/statGlobal.js' %}"></script>
        </div>
    </div>
    <div>
<p>
    Les vitesses moyennes proches entre le 10 km et le semi-marathon nous montrent que la décélération de vitesse est probablement moindre entre l'ensemble
    des résultats effectivement mesuré au 10 km et au semi-marathon que celle existant entre
    des performances pour des coureurs équivalents. Les scores de performance étant basé sur la médiane de vitesse des participants de la course, on a pu donc sous-évaluer
    les performances pour les coureurs ayant participé a des distances longues et sur-évaluer les performances pour des distances plus courtes, à cause d'une compétitivité
    différente au départ de ces courses. Pour améliorer les scores des performances
    <a href="{% url 'graph:score_distribution' %}">voir ici la feature montrant le comportement des scores de performances</a>
    nous aurions pu à partir de la littérature sur la baisse de performance en fonction de la distance et de la catégorie dans la course à pied, comprendre et ajuster, l'augmentation du niveau moyen des coureurs participants à des distances plus longues.
    Le biais de compétitivité au départ des courses selon leur distance nuit donc probablement au calcul des scores de performance.
</p>
    <p>
        Toutefois l'originalité de notre approche a été d'utiliser des résultats d'événements grand public peu étudiés par la littérature
        et les changements de vitesses entre les distances sont probablement différents (sous estimé) par rapport aux coureurs élites
        qui gérent mieux leurs efforts durant la course et minimisent les phénomènes de baisse de vitesse dû à l'augmentation de la distance comparativement à
        des coureurs non professionnels qui sont entrainés moins spécifiquement pour ces distances que les coureurs élites.
    </p>
    <p>
        Une dernière possibilité d'amélioration des scores de performances aurait donc été d'utiliser les coureurs regroupés de manière hypothétique comme étant une seule et même personne, et
        d'analyser leur baisse de vitesse avec l'augmentation de la distance, en moyenne et d'utiliser la régression de cette baisse de vitesse
        selon la distance pour chaque catégorie comme base de normalisation. Cette base permettrait ainsi d'éviter le biais de séléction des coureurs au départ d'un événement en fonction
        de la distance et la sous-évaluation pour les grandes distances de la performance (et sur-évaluation pour les petites distances de la performance) qui en résulte.
    </p><p>
        Le score global, prenant en compte le temps de course il peut avoir tendance à minimiser cette erreur. Toutefois, une normalisation par catégorie de la performance
        peut être intéressante et sera peut-être étudié plus tard.
    </p>
    </div>
{% endblock %}