DataTest/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
# Configuration Dash

urlpatterns = [
# Configuration requise pour django-plotly-dash
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('', views.home, name='home'),

    path('scholar_and_cv/', views.scholar_and_cv, name='scholar_and_cv'),
    path('polls/', include('polls.urls')),
    path('agri/', include('agri.urls')),
    path('admin/', admin.site.urls),
    path('graph/', include('graph.urls')),
    path('bubble_sort/', include('bubble_sort.urls')),
    # Intégration de l'app Dash sous le préfixe 'agri/demo/'
    path('agri/demo/', include([
    path('', include('dashapp.urls', namespace='dashapp')),  # Correction clé
    path('/api/', include('dashapp.urls', 'api')),  # Inclusion du namespace API
    path('dash-components/', include('django_plotly_dash.urls')),  # Routes Dash
    ])),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agri/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# Configuration Dash

urlpatterns = [
    path('', views.home, name='app_presentation'),
    path('demo/', views.ParcelView.as_view(), name='parcel_viewer'),
    path('ndvi/', views.NDVIView.as_view(), name='ndvi_view'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashapp/urls.py
from django.urls import path
from . import views

app_name = 'dashapp'

urlpatterns = [
    path('parcelles/', views.dash_view, name='parcelle_analysis'),
path('api/ml-pipeline/', views.process_ml_pipeline, name='ml_pipeline'),

path('api/save-points/', views.save_points, name='save_points'),
    path('ml-results/<uuid:train_result_id>/<uuid:pred_result_id>/',  # Ajout des UUID
         views.ml_results_view,
         name='ml_results'),
]

agri/models.py
# models.py
from django.db import models
import os
from django.conf import settings
import uuid
from django.utils import timezone
from hashlib import sha256

class SatelliteImage:
    def __init__(self, date):
        self.date = date
        # Chemin vers l'image TIFF multi-bandes
        self.tiff_path = os.path.join('satellite_data', 'Boulinsard', '12bands', f'{date}_S2A-12band.TIFF')
        # Chemin vers l'image lai
        self.lai_path = os.path.join('satellite_data', 'Boulinsard', 'lai', f'{date}_LAI.jpg')

    def get_band(self, band_index):
        """Récupère une bande spécifique de l'image TIFF"""
        import rasterio
        with rasterio.open(self.tiff_path) as src:
            return src.read(band_index)


class Parcel(models.Model):
    name = models.CharField(max_length=100)

    def get_available_dates(self):
        """Récupère les dates disponibles en parcourant le dossier"""
        tiff_dir = os.path.join(settings.STATIC_ROOT, 'satellite_data','Boulinsard', '12bands')
        dates = []
        for file in os.listdir(tiff_dir):
            if file.endswith('12band.TIFF'):
                date = file.split('_')[0]
                dates.append(date)
        return sorted(dates)

    def get_image_for_date(self, date):
        """Retourne un objet SatelliteImage pour une date donnée"""
        return SatelliteImage(date)

agri/views.py
from venv import logger
from django.http import HttpResponseServerError
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from pydantic import ValidationError
from .services.image_processor import ParcelImageProcessor
from django.conf import settings
from .schemas import GridCellSchema
from django.views.generic import TemplateView
from django.http import JsonResponse
from .services.ndvi_plot import *
from django.views import View

def home(request):
    context = {
        'message': 'Cette application vous aide à gérer votre exploitation agricole.'
    }
    return render(request, 'agri/app_presentation.html', context)

def get_available_dates():
    tiff_dir = os.path.join(settings.STATIC_ROOT, 'satellite_data','Boulinsard', '12bands')
    dates = []
    for file in os.listdir(tiff_dir):
        if file.endswith('12band.TIFF'):
            date = file.split('_')[0]  # Extrait la date du nom de fichier
            dates.append(date)
    return sorted(dates)

@method_decorator(csrf_exempt, name='dispatch')
class ParcelView(TemplateView):
    template_name = 'agri/parcel_viewer.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Partie commune inchangée
        context['dates'] = get_available_dates()
        context['initial_date'] = context['dates'][0]
        parcel_path = "Boulinsard"
        # Traitement des données principales
        processor = ParcelImageProcessor(context['initial_date'], 4, 4, parcel_path)
        # Génération de l'image RGB
        context['rgb_image_path'] = processor.save_rgb_image()
        # Traitement de la grille
        raw_grid = processor.create_pixel_grid()
        try:
            validated_grid = [GridCellSchema.model_validate(cell).model_dump() for cell in raw_grid]
        except ValidationError as e:
            logger.error("Erreur de validation : %s", e)
            return HttpResponseServerError()

        pixel_grid = processor.serialize_grid(raw_grid)
        grid_session_data = processor.get_grid_ids_and_data(raw_grid)

        # Mise à jour de la session
        self.request.session.update({
            'loaded_ids': grid_session_data['ids'],
            'grid_cells': grid_session_data['data']
        })
        self.request.session.modified = True
        # Données conservées pour la partie non-Dash
        context['pixel_grid'] = pixel_grid

        context['session_key'] = self.request.session.session_key
        return context



    @csrf_exempt
    def post(self, request, *args, **kwargs):
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            try:
                action = request.POST.get('action')
                if action == 'change_date':
                    date = request.POST.get('date')
                    column_size = request.POST.get('column_size')
                    row_size = request.POST.get('row_size')
                    parcel_path = "Boulinsard"

                    # Création et sauvegarde de la nouvelle image
                    processor2 = ParcelImageProcessor(date, int(column_size), int(row_size), parcel_path)
                    rgb_image_path = processor2.save_rgb_image()

                    raw_grid2 = processor2.create_pixel_grid()
                    pixel_grid2 = processor2.serialize_grid(raw_grid2)
                    # Récupération des données structurées
                    grid_session_data = processor2.get_grid_ids_and_data(raw_grid2)
                    # Réinitialisation complète
                    # Stockage direct dans la session comme vous le souhaitez
                    try:
                        self.request.session.flush()
                    except:
                        print("cant reset session")
                    try:
                        self.request.session['loaded_ids'] = grid_session_data['ids']
                        self.request.session['grid_cells'] = grid_session_data['data']
                    except:
                        try:
                            self.request.session['loaded_ids'].update(grid_session_data['ids'])
                            self.request.session['grid_cells'].update(grid_session_data['data'])
                        except:
                            print("cant update data")

                    return JsonResponse({
                            'rgb_image_path': rgb_image_path,
                            'pixel_grid': pixel_grid2  # Suppression de la sérialisation superflue
                        }, safe=False)

                elif action == 'get_zone_by_id':
                    cell_id = request.POST.get('cell_id')
                    date = request.POST.get('date')
                    column_size = request.POST.get('column_size')
                    row_size = request.POST.get('row_size')
                    # Vérifier la cohérence de la date
                    current_grid = request.session.get('grid_cells')
                    cell_data = current_grid.get(cell_id)
                    if not cell_data:
                        return JsonResponse({'error': 'Zone non trouvée'}, status=404)
                    parcel_path = 'Boulinsard'
                    processor3 = ParcelImageProcessor(date, int(column_size), int(row_size), parcel_path)

                    zone_data = processor3.get_zone_data(cell_data)

                    # Avant l'envoi au serveur
                    for band in zone_data['bands']:
                        zone_data['bands'][band] = zone_data['bands'][band].item()  # Convertit np.float32 en float natif
                    try:
                        return JsonResponse({
                            'coordinates': zone_data['coordinates'],
                            'bands': zone_data['bands']
                        })
                    except Exception as e:
                        logger.error(f"Erreur critique: {str(e)}", exc_info=True)
                        return JsonResponse({'error': 'Erreur de traitement'}, status=500)
            except Exception as e:
                return JsonResponse({'error': str(e)}, status=500)

        return JsonResponse({'error': 'Requête non autorisée'}, status=400)

class NDVIView(View):
    def get(self, request, *args, **kwargs):
        # Récupérer la date depuis les paramètres GET ou utiliser une date par défaut
        specific_date = request.GET.get('date', '2021-03-08')  # Date par défaut pour l'initialisation

        try:
            converted_date = datetime.strptime(specific_date, '%Y-%m-%d').date()
        except ValueError:
            return render(request, 'agri/ndvi_template.html', {'error': 'Date invalide'})

        # Obtenir les données NDVI
        ndvi_data, date_df = create_ndvi_cube()
        first_layer = date_df.loc[date_df['sorted_date'] == converted_date].index[0]
        info_last_count = date_df.loc[date_df['sorted_date'] == converted_date].iloc[-1]
        print('info_first_layer', first_layer)

        print('test')
        # Extraire les valeurs de current_date et co
        last_count = info_last_count['number']
        print('layer ',first_layer, last_count)
        # Générer le graphique NDVI
        plot_html = generate_ndvi_plot(ndvi_data, first_layer, last_count)

        # Retourner le contexte au template
        return render(request, 'agri/ndvi_template.html', {'plot_html': plot_html})

agri/templates/agri/app_presentation.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Presentation de la future application d'agriculture digitale</title>
</head>
<body>
<div class="content-container">
<link rel="stylesheet" href="{% static 'css/agri.css' %}">
    <h3>Introduction</h3>
<div class="text-box">

    <p>Passionné par la science du végétal et ses mécanismes moléculaires, j'ai travaillé à l'INRAE et à Limagrain dans le
        cadre de recherches exploratoires visant à améliorer les qualités des plantes destinées à l'agriculture. Cette passion
        m'a mené à diverses conclusions concernant les besoins de l'agriculture et les technologies qui y sont rattachées.
        D'abord, l'agriculture fait face à toujours plus de demandes et de nombreux stress économiques et environnementaux
        lui sont d'années en années imposées. Les agriculteurs ont donc besoin de technologies toujours plus sophistiquées pour
        répondre à ces contraintes. </p><p>C'est pour répondre à ces problématiques que j'ai décidé de m'engager dans un
        double cursus alliant à la fois des compétences de pointes dans 'l'ingénieurie du végétale' et en datascience car
        c'est l'alliance de ces compétences qui est pour moi la clef de voute pour la résolution des problématiques
        concernant l'agriculture. <p></p>Ces problématiques peuvent concerner aussi bien la réduction des intrants que la
        recherche & développement dans l'amélioration variétale. C'est pourquoi j'ai décidé de créer cette application qui
        a partir d'images satellites de champs de diverses grandes cultures et sur divers territoires disponibles en open
        source de réaliser la prédiction du rendement ou l'évolution de divers indicateurs d'intérêt du champ. L'application
        développée aura pour objectif de montrer comment prédire du rendement par diverses méthodes de datascience allant
        de simple moteur de règles jusqu'à l'utilisation d'intelligence artificielle en passant par le machine et le deep
        learning. </p>
</div>
    <div class="demo-button-container">
            <a href="{% url 'parcel_viewer' %}" class="demo-button">Voir la démonstration</a>
        </div>
</div>
</body>
{% endblock %}

agri/templates/agri/ndvi_template.html
<head>
    <title>NDVI Plot</title>
</head>
<body>

<div id="ndvi-container">
    {{ plot_html|safe }}
    </div>
</body>

agri/templates/agri/parcel_viewer.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    <head>

</head>
    {% csrf_token %}
    <script>
    const STATIC_URL = '{% static "" %}';
</script>
        <link rel="stylesheet" href="{% static 'css/parcel_wiewing.css' %}">
    <section>
    <div id="col1">
    <div class="parcel-viewer">

        <!-- Ajouter un conteneur dédié avec ID explicite -->
        <div id="grid-container">
            <div class="viewer-container">
                <div class="image-container" id="parcel-image">
                    <img id="satellite-image" src="{% static rgb_image_path %}" alt="Parcel view">
                </div>
            </div>
        </div>
                    <div class="date-selector">
            <select id="date-picker">
                {% for date in dates %}
                    <option value="{{ date }}" {% if date == initial_date %}selected{% endif %}>
                        {{ date }}
                    </option>
                {% endfor %}
            </select>

            <script type="application/json" id="grid-data">
                {{ pixel_grid|safe }}
            </script>
        </div>
                <div class="band-info-panel">
<h3>Valeurs des Bandes</h3>
<table id="band-values-table">
        <thead>
            <tr>
                <th>Bande</th>
                <th>Nom Usuel</th>
                <th>Caractéristiques</th>
                <th>Valeur Moyenne</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Bande 1</td>
                <td>Aérosol côtier</td>
                <td>443 nm (60 m)</td>
                <td id="band-1-value">-</td>
            </tr>
            <tr>
                <td>Bande 2</td>
                <td>Bleu</td>
                <td>490 nm (10 m)</td>
                <td id="band-2-value">-</td>
            </tr>
            <tr>
                <td>Bande 3</td>
                <td>Vert</td>
                <td>560 nm (10 m)</td>
                <td id="band-3-value">-</td>
            </tr>
            <tr>
                <td>Bande 4</td>
                <td>Rouge</td>
                <td>665 nm (10 m)</td>
                <td id="band-4-value">-</td>
            </tr>
            <tr>
                <td>Bande 5</td>
                <td>Bordure rouge (Red Edge)</td>
                <td>705 nm (20 m)</td>
                <td id="band-5-value">-</td>
            </tr>
            <tr>
                <td>Bande 6</td>
                <td>Bordure rouge (Red Edge)</td>
                <td>740 nm (20 m)</td>
                <td id="band-6-value">-</td>
            </tr>
            <tr>
                <td>Bande 7</td>
                <td>Bordure rouge (Red Edge)</td>
                <td>783 nm (20 m)</td>
                <td id="band-7-value">-</td>
            </tr>
            <tr>
                <td>Bande 8</td>
                <td>NIR (Proche infrarouge)</td>
                <td>842 nm (10 m)</td>
                <td id="band-8-value">-</td>
            </tr>
            <tr>
                <td>Bande 8A</td>
                <td>NIR étroit (Proche infrarouge étroit)</td>
                <td>865 nm (20 m)</td>
                <td id="band-8a-value">-</td>
            </tr>
            <tr>
                <td>Bande 9</td>
                <td>Vapeur d'eau</td>
                <td>945 nm (60 m)</td>
                <td id="band-9-value">-</td>
            </tr>
            <tr>
                <td>Bande 10</td>
                <td>Cirrus (SWIR)</td>
                <td>1375 nm (60 m)</td>
                <td id="band-10-value">-</td>
            </tr>
            <tr>
                <td>Bande 11</td>
                <td>SWIR 1 (Infrarouge à ondes courtes)</td>
                <td>1610 nm (20 m)</td>
                <td id="band-11-value">-</td>
            </tr>
            <tr>
                <td>Bande 12</td>
                <td>SWIR 2 (Infrarouge à ondes courtes)</td>
                <td>2190 nm (20 m)</td>
                <td id="band-12-value">-</td>
            </tr>
    </tbody>
</table>

        </div>
    </div>
    </div>
    <!-- Nouvelle division pour le bouton -->
<div id="center-button">
    <button onclick="window.location.href='{% url 'dashapp:parcelle_analysis' %}'">
        Accéder au Machine Learning de prédiction de Rendement
    </button>
</div>
<div id="col2">
    <h2>NDVI 3d Plot</h2>
    <iframe id='ndvi_view' src="{% url 'ndvi_view' %}" width="100%" height="1250px" frameborder="0"></iframe>
</div>
</section>
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
    <script src="{% static 'js/parcelViewing.js' %}"></script>

{% endblock %}